### ISSUE TITLE
Google game services login error

### ISSUE THREAD

**Issue by Astroxslurg** [TDT4240-Software-Architecture-group-20/game-project#53]
I can't sign in any other account than the one that I've been using up to now.

I need to use two accounts in order to test playing against my self, so I found my old phone and set it up with another google account. but all I get is a popup saying "There was an issue with sign in. Please try again later.". This is a dump of the log:
```
04-09 22:39:41.588 4179-4179/car.superfun.game D/CarSuperFun: signInSilently()
04-09 22:39:41.599 4179-4841/car.superfun.game D/EGL_emulation: eglMakeCurrent: 0xae614a20: ver 2 0 (tinfo 0xae612680)
04-09 22:39:41.599 4179-4841/car.superfun.game I/AndroidGraphics: resumed
04-09 22:39:41.628 4179-4228/car.superfun.game D/EGL_emulation: eglMakeCurrent: 0xaa9b04e0: ver 2 0 (tinfo 0xaaac4e90)
04-09 22:39:41.636 4179-4228/car.superfun.game E/Surface: getSlotFromBufferLocked: unknown buffer: 0xae432aa0
04-09 22:39:41.642 4179-4179/car.superfun.game D/CarSuperFun: signInSilently(): failure
                                                              com.google.android.gms.common.api.ApiException: 4: 
                                                                  at com.google.android.gms.common.internal.zzb.zzy(Unknown Source)
                                                                  at com.google.android.gms.common.internal.zzbk.zzz(Unknown Source)
                                                                  at com.google.android.gms.common.internal.zzbl.zzr(Unknown Source)
                                                                  at com.google.android.gms.common.api.internal.BasePendingResult.zzc(Unknown Source)
                                                                  at com.google.android.gms.common.api.internal.BasePendingResult.setResult(Unknown Source)
                                                                  at com.google.android.gms.auth.api.signin.internal.zzg.zza(Unknown Source)
                                                                  at com.google.android.gms.auth.api.signin.internal.zzt.onTransact(Unknown Source)
                                                                  at android.os.Binder.execTransact(Binder.java:453)
```

I tried login into the account I have used earlier (kkrorkk@gmail.com) and that was no problem, but I need two different accounts...

I tried using the emulator (I got GPGS set up on it without problem), and I tried using my GF's old samsung tablet with her user... Got the same error every time, so I have concluded that there is something wrong.

**Comment by SueLee0610** [comment]
It's probably because we haven't added the new account(that you're trying to play against with) to the test accounts? If you let me know the email of your girlfriend then we can try again after adding it!

**Comment by Astroxslurg** [comment]
Ah! Of course! 😃😃😃
Add KristianTrandem@gmail.com then :)
Thank You! 😄 💃
